//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindEntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Hight { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Type1 { get; set; }
        public Nullable<int> kg { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
